spring:
  config:
    activate:
      on-profile: dev

  datasource:
    username: root
    password: emmmm000

springdoc:
  default-flat-param-object: true
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
#knife4j:
#  enable: true
#  setting:
#    language: zh_cn
#    enable-dynamic-parameter: true

log:
  path: D:\code\kotlin\Note\
  root:
    level: info
