spring:
  application:
    name: Note
  profiles:
    active: dev

  datasource:
    url: jdbc:mysql://127.0.0.1:3306/note?useSSL=false&useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8&allowMultiQueries=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      pool-name: HikariCPDatasource
      minimum-idle: 5
      idle-timeout: 180000
      maximum-pool-size: 10
      auto-commit: true
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1

  data:
    redis:
      database: 2
      host: 127.0.0.1
      port: 6379
      password: emmmm000
      jedis:
        pool:
          max-active: 20
          max-wait: -1
          max-idle: 10
          min-idle: 0
      connect-timeout: 2000

server:
  port: 8080
  servlet:
    context-path: /api

mybatis:
  type-aliases-package: io.github.hcisme.note.entity.pojo,io.github.hcisme.note.entity.query
  configuration:
    map-underscore-to-camel-case: true
